language: go

services:
  - docker

before_install:
  - docker-compose -f docker-compose.test.yml up -d

script: 
  - go test .

before_install:
  - docker-compose -f docker-compose.test.yml down