language: go

services:
  - docker

branches:
  only:
    - master

before_install:
  # this 3 domain name use for searching docker container
  - sudo sh -c "echo '\n127.0.0.1\tmgo1' >> /etc/hosts"
  - sudo sh -c "echo '\n127.0.0.1\tmgo2' >> /etc/hosts"
  - sudo sh -c "echo '\n127.0.0.1\tmgo3' >> /etc/hosts"
  - docker-compose -f ./test/docker-compose.yml up --build -d

script: 
  - sleep 60 | echo "wait for mongo cluster to finish setup"
  - go test -race -timeout 30s .

after_script:
  - docker-compose -f ./test/docker-compose.yml down --volume --remove-orphans